// Test data for development and testing purposes
// This data structure matches the CSV data format expected by the application

const testData = [
  {
    sbfCode: "Jul2025",
    project_town: "Punggol",
    project_name: "Punggol Point Parcels A & B",
    flat_type: "4-Room",
    block: "123A",
    unit: "01-234",
    price: 580000,
    size_sqm: 93,
    price_psf: 580,
    approximate_resale_value: 650000,
    max_lease: 99,
    nearest_mrt: "Punggol MRT",
    walking_distance_in_m: 400,
    walking_time_in_mins: 5,
    nearest_mrt_lrt: "Punggol MRT",
    mrt_lrt_walking_distance_in_m: 400,
    mrt_lrt_walking_time_in_mins: 5,
    chinese_quota: 1,
    malay_quota: 0,
    indian_and_other_races_quota: 1,
    top_delay_date: "2027-06-01",
    repurchased: false
  },
  {
    sbfCode: "Jul2025",
    project_town: "Tengah",
    project_name: "Tengah Garden District",
    flat_type: "3-Room",
    block: "456B",
    unit: "05-678",
    price: 420000,
    size_sqm: 68,
    price_psf: 574,
    approximate_resale_value: 480000,
    max_lease: 99,
    nearest_mrt: "Bukit Gombak MRT",
    walking_distance_in_m: 800,
    walking_time_in_mins: 10,
    nearest_mrt_lrt: "Bukit Gombak MRT",
    mrt_lrt_walking_distance_in_m: 800,
    mrt_lrt_walking_time_in_mins: 10,
    chinese_quota: 1,
    malay_quota: 1,
    indian_and_other_races_quota: 0,
    top_delay_date: "2027-12-01",
    repurchased: false
  },
  {
    sbfCode: "Jul2025",
    project_town: "Kallang",
    project_name: "Kallang Riverside",
    flat_type: "5-Room",
    block: "789C",
    unit: "10-123",
    price: 780000,
    size_sqm: 110,
    price_psf: 659,
    approximate_resale_value: 850000,
    max_lease: 99,
    nearest_mrt: "Stadium MRT",
    walking_distance_in_m: 300,
    walking_time_in_mins: 4,
    nearest_mrt_lrt: "Stadium MRT",
    mrt_lrt_walking_distance_in_m: 300,
    mrt_lrt_walking_time_in_mins: 4,
    chinese_quota: 0,
    malay_quota: 1,
    indian_and_other_races_quota: 1,
    top_delay_date: "2027-09-01",
    repurchased: true
  },
  {
    sbfCode: "Feb2026",
    project_town: "Jurong East",
    project_name: "Jurong Innovation District",
    flat_type: "4-Room",
    block: "321D",
    unit: "08-456",
    price: 520000,
    size_sqm: 88,
    price_psf: 550,
    approximate_resale_value: 580000,
    max_lease: 99,
    nearest_mrt: "Jurong East MRT",
    walking_distance_in_m: 200,
    walking_time_in_mins: 3,
    nearest_mrt_lrt: "Jurong East MRT",
    mrt_lrt_walking_distance_in_m: 200,
    mrt_lrt_walking_time_in_mins: 3,
    chinese_quota: 1,
    malay_quota: 0,
    indian_and_other_races_quota: 1,
    top_delay_date: "2028-03-01",
    repurchased: false
  },
  {
    sbfCode: "Feb2026", 
    project_town: "Tampines",
    project_name: "Tampines GreenRidges",
    flat_type: "2-Room",
    block: "654E",
    unit: "15-789",
    price: 320000,
    size_sqm: 47,
    price_psf: 632,
    approximate_resale_value: 380000,
    max_lease: 99,
    nearest_mrt: "Tampines MRT",
    walking_distance_in_m: 600,
    walking_time_in_mins: 8,
    nearest_mrt_lrt: "Tampines MRT",
    mrt_lrt_walking_distance_in_m: 600,
    mrt_lrt_walking_time_in_mins: 8,
    chinese_quota: 1,
    malay_quota: 1,
    indian_and_other_races_quota: 1,
    top_delay_date: "2028-08-01",
    repurchased: false
  }
];

export default testData;